cask_args appdir: "/Applications"

tap "heroku/brew"
tap "motemen/ghq"
tap "sanemat/font"

brew "anyenv"
brew "autoconf"
brew "BZip2"
brew "composer"
brew "ghq"
brew "git"
brew "heroku"
brew "icu4c"
brew "jq"
brew "krb5"
brew "libedit"
brew "libiconv"
brew "libjpeg"
brew "libpng"
brew "libxml2"
brew "libzip"
brew "mysql"
brew "oniguruma"
brew "openssl@1.1"
brew "peco"
brew "pkg-config"
brew "postgresql"
brew "sqlite"
brew "tidy-html5"
brew "tmux"
brew "vim"
brew "yarn"

cask "adobe-creative-cloud"
cask "android-studio"
cask "alfred"
cask "chatwork"
cask "cheatsheet"
cask "discord"
cask "docker"
cask "evernote"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "megasync"
cask "mysqlworkbench"
cask "postman"
cask "spectacle"
cask "tableplus"
cask "thunderbird"
cask "visual-studio-code"
cask "zoomus"

mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "OneDrive", id: 823766827
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835